//ERRORS
export const GET_ERRORS = 'GET_ERRORS';
//AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_ADMIN = 'ADD_ADMIN';
export const ADD_ADMIN = 'CHANGE_ADMIN';
export const REMOVE_ADMIN = 'REMOVE_ADMIN';
//REQUESTS
export const GET_REQUESTS = 'GET_REQUESTS';
export const MAKE_REQUEST = 'MAKE_A_REQUEST';
export const REQUESTS_LOADING = 'REQUESTS_LOADING';
export const START_HELPING = 'START_HELPING';
export const DELETE_REQUEST = 'DELETE_REQUEST';
//STATS
export const GET_STATS = 'GET_STATS';
export const GET_STATS_225 = 'GET_STATS_225';
export const GET_STATS_325 = 'GET_STATS_325';
export const GET_LOGGED_IN_USERS = 'GET_LOGGED_IN_USERS';
//TERMS
export const GET_TERMS = 'GET_TERMS';
export const CREATE_TERM = 'CREATE_TERM';
export const ACTIVATE_TERM = 'ACTIVATE_TERM';
export const DELETE_TERM = 'DELETE_TERM';